// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKcxxWVKXJ4jJphYdlDAVrYQvr8VnRbgc',
    appId: '1:174661741186:web:910e2cc1703d7417aa229b',
    messagingSenderId: '174661741186',
    projectId: 'fruits-4b686',
    authDomain: 'fruits-4b686.firebaseapp.com',
    storageBucket: 'fruits-4b686.firebasestorage.app',
    measurementId: 'G-T2HKX0PEXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKSSLr8Fgiygwbz7ONmQDtObBxEA4CYtQ',
    appId: '1:174661741186:android:aa4053748da32653aa229b',
    messagingSenderId: '174661741186',
    projectId: 'fruits-4b686',
    storageBucket: 'fruits-4b686.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk-ZNLg9fqLhdjv6Qyx8vcLaLvZqfMvik',
    appId: '1:174661741186:ios:06382c7b9edfb2feaa229b',
    messagingSenderId: '174661741186',
    projectId: 'fruits-4b686',
    storageBucket: 'fruits-4b686.firebasestorage.app',
    androidClientId: '174661741186-80bsqcshasund9mkcs53crm32odu6t9f.apps.googleusercontent.com',
    iosClientId: '174661741186-fecph1l1io9a54pd9p2poh5ovh6hlhnd.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruits',
  );

}